/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Car.gltf -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model/source/HelloAnim.glb')
  return (
    <group {...props} dispose={null} scale={0.3}>
      <mesh geometry={nodes.Car_Modified.geometry} material={materials.Car_Modified} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/model/source/Car.gltf')
