/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./models/mushroom.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three';

export function Mushroom(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/mushroom.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    group.current.position.y = -2.5;
    props.mashroomActiosRef.current = actions
    actions.DefaultHelloAnim.setLoop(THREE.LoopOnce).play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="rig">
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <group name="Cube003">
            <skinnedMesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials.body} skeleton={nodes.Mesh.skeleton} />
            <skinnedMesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Material} skeleton={nodes.Mesh_1.skeleton} />
            <skinnedMesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials.Eyes} skeleton={nodes.Mesh_2.skeleton} />
            <skinnedMesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={materials.balls} skeleton={nodes.Mesh_3.skeleton} />
          </group>
        </group>
        <group name="WGT-rig_spine_fk" position={[-0.014, 0.728, -0.017]} rotation={[1.823, 0.031, 0]} scale={0.152} />
        <group name="WGT-rig_spine_fk001" position={[-0.015, 0.837, 0]} rotation={[1.724, 0.009, -0.002]} scale={0.11} />
        <group name="WGT-rig_spine_fk002" position={[-0.015, 0.837, 0]} rotation={[1.529, -0.01, 0.001]} scale={0.133} />
        <group name="WGT-rig_spine_fk003" position={[-0.014, 0.97, -0.006]} rotation={[1.551, 0.021, 0]} scale={0.276} />
        <group name="WGT-rig_tweak_spine" position={[-0.009, 0.581, -0.055]} rotation={[1.823, 0.031, 0]} scale={0.076} />
        <group name="WGT-rig_tweak_spine001" position={[-0.014, 0.728, -0.017]} rotation={[1.724, 0.009, -0.002]} scale={0.055} />
        <group name="WGT-rig_tweak_spine002" position={[-0.015, 0.837, 0]} rotation={[1.529, -0.01, 0.001]} scale={0.066} />
        <group name="WGT-rig_tweak_spine003" position={[-0.014, 0.97, -0.006]} rotation={[1.551, 0.021, 0]} scale={0.138} />
        <group name="WGT-rig_tweak_spine004" position={[-0.019, 1.246, -0.011]} rotation={[1.585, -0.011, 0.019]} scale={0.165} />
        <group name="WGT-rig_torso" position={[-0.012, 0.655, -0.036]} scale={0.403} />
        <group name="WGT-rig_hips" position={[-0.009, 0.581, -0.055]} rotation={[1.823, 0.031, 0]} scale={0.168} />
        <group name="WGT-rig_chest" position={[-0.014, 0.97, -0.006]} rotation={[1.551, 0.021, 0]} scale={0.224} />
        <group name="WGT-rig_shoulderL" position={[-0.001, 1.193, 0.068]} rotation={[0.221, -1.312, 0.291]} scale={0.357} />
        <group name="WGT-rig_upper_arm_parentL" position={[0.37, 1.193, -0.027]} rotation={[-2.546, -1.195, 2.536]} scale={0.058} />
        <group name="WGT-rig_upper_arm_fkL" position={[0.37, 1.193, -0.027]} rotation={[-2.546, -1.195, 2.536]} scale={0.234} />
        <group name="WGT-rig_forearm_fkL" position={[0.587, 1.144, 0.044]} rotation={[-2.881, -1.057, 2.232]} scale={0.298} />
        <group name="WGT-rig_hand_fkL" position={[0.846, 1.107, 0.186]} rotation={[-2.381, -0.695, 2.628]} scale={0.09} />
        <group name="WGT-rig_upper_arm_ikL" position={[0.37, 1.193, -0.027]} rotation={[-2.546, -1.195, 2.536]} scale={0.234} />
        <group name="WGT-rig_upper_arm_ik_targetL" position={[0.751, 0.931, -0.411]} rotation={[2.703, 0.316, -1.242]} scale={0.066} />
        <group name="WGT-rig_hand_ikL" position={[0.846, 1.107, 0.186]} rotation={[-2.381, -0.695, 2.628]} scale={0.09} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleL" position={[0.587, 1.144, 0.044]} rotation={[Math.PI / 2, 0, -1.352]} scale={0.529} />
        <group name="WGT-rig_upper_arm_tweakL" position={[0.37, 1.193, -0.027]} rotation={[-2.546, -1.195, 2.536]} scale={0.058} />
        <group name="WGT-rig_upper_arm_tweakL001" position={[0.478, 1.168, 0.009]} rotation={[-2.546, -1.195, 2.536]} scale={0.058} />
        <group name="WGT-rig_forearm_tweakL" position={[0.587, 1.144, 0.044]} rotation={[-2.881, -1.057, 2.232]} scale={0.074} />
        <group name="WGT-rig_forearm_tweakL001" position={[0.717, 1.125, 0.115]} rotation={[-2.881, -1.057, 2.232]} scale={0.074} />
        <group name="WGT-rig_hand_tweakL" position={[0.846, 1.107, 0.186]} rotation={[-2.381, -0.695, 2.628]} scale={0.022} />
        <group name="WGT-rig_shoulderR" position={[-0.018, 1.193, 0.068]} rotation={[-2.92, -1.298, 0.291]} scale={-0.339} />
        <group name="WGT-rig_upper_arm_parentR" position={[-0.37, 1.193, -0.027]} rotation={[0.596, -1.195, 2.536]} scale={-0.058} />
        <group name="WGT-rig_upper_arm_fkR" position={[-0.37, 1.193, -0.027]} rotation={[0.596, -1.195, 2.536]} scale={-0.234} />
        <group name="WGT-rig_forearm_fkR" position={[-0.587, 1.144, 0.044]} rotation={[0.261, -1.057, 2.232]} scale={-0.298} />
        <group name="WGT-rig_hand_fkR" position={[-0.846, 1.107, 0.186]} rotation={[0.761, -0.695, 2.628]} scale={-0.09} />
        <group name="WGT-rig_upper_arm_ikR" position={[-0.37, 1.193, -0.027]} rotation={[0.596, -1.195, 2.536]} scale={-0.234} />
        <group name="WGT-rig_upper_arm_ik_targetR" position={[-0.751, 0.931, -0.411]} rotation={[-0.438, 0.316, -1.242]} scale={-0.066} />
        <group name="WGT-rig_hand_ikR" position={[-0.846, 1.107, 0.186]} rotation={[0.761, -0.695, 2.628]} scale={-0.09} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleR" position={[-0.587, 1.144, 0.044]} rotation={[-Math.PI / 2, 0, -1.352]} scale={-0.529} />
        <group name="WGT-rig_upper_arm_tweakR" position={[-0.37, 1.193, -0.027]} rotation={[0.596, -1.195, 2.536]} scale={-0.058} />
        <group name="WGT-rig_upper_arm_tweakR001" position={[-0.478, 1.168, 0.009]} rotation={[0.596, -1.195, 2.536]} scale={-0.058} />
        <group name="WGT-rig_forearm_tweakR" position={[-0.587, 1.144, 0.044]} rotation={[0.261, -1.057, 2.232]} scale={-0.074} />
        <group name="WGT-rig_forearm_tweakR001" position={[-0.717, 1.125, 0.115]} rotation={[0.261, -1.057, 2.232]} scale={-0.074} />
        <group name="WGT-rig_hand_tweakR" position={[-0.846, 1.107, 0.186]} rotation={[0.761, -0.695, 2.628]} scale={-0.022} />
        <group name="WGT-rig_neck" position={[-0.019, 1.246, -0.011]} rotation={[1.585, -0.011, 0.019]} scale={0.33} />
        <group name="WGT-rig_head" position={[-0.016, 1.576, -0.007]} rotation={[1.17, -0.003, -0.008]} scale={2.502} />
        <group name="WGT-rig_thigh_parentL" position={[0.344, 0.638, -0.012]} rotation={[-1.652, 0.191, -0.12]} scale={0.047} />
        <group name="WGT-rig_thigh_fkL" position={[0.344, 0.638, -0.012]} rotation={[-1.652, 0.191, -0.12]} scale={0.189} />
        <group name="WGT-rig_shin_fkL" position={[0.308, 0.453, 0.003]} rotation={[-1.6, 0.185, -0.13]} scale={0.183} />
        <group name="WGT-rig_foot_fkL" position={[0.275, 0.273, 0.008]} rotation={[-1.616, -0.085, 1.08]} scale={0.193} />
        <group name="WGT-rig_foot_fkL003" position={[0.291, 0.08, 0.017]} rotation={[3.134, 0.194, 3.119]} scale={0.226} />
        <group name="WGT-rig_thigh_ikL" position={[0.344, 0.638, -0.012]} rotation={[-1.652, 0.191, -0.12]} scale={0.189} />
        <group name="WGT-rig_thigh_ik_targetL" position={[0.263, 0.482, 0.371]} rotation={[-0.079, -0.123, -0.005]} scale={0.047} />
        <group name="WGT-rig_foot_ikL" position={[0.275, 0.273, 0.008]} scale={0.193} />
        <group name="WGT-rig_VIS_thigh_ik_poleL" position={[0.308, 0.453, 0.003]} rotation={[Math.PI / 2, 0, -0.32]} scale={0.372} />
        <group name="WGT-rig_thigh_tweakL" position={[0.344, 0.638, -0.012]} rotation={[-1.652, 0.191, -0.12]} scale={0.047} />
        <group name="WGT-rig_thigh_tweakL001" position={[0.326, 0.546, -0.005]} rotation={[-1.652, 0.191, -0.12]} scale={0.047} />
        <group name="WGT-rig_shin_tweakL" position={[0.308, 0.453, 0.003]} rotation={[-1.6, 0.185, -0.13]} scale={0.046} />
        <group name="WGT-rig_shin_tweakL001" position={[0.291, 0.363, 0.005]} rotation={[-1.6, 0.185, -0.13]} scale={0.046} />
        <group name="WGT-rig_foot_tweakL" position={[0.275, 0.273, 0.008]} rotation={[-1.616, -0.085, 1.08]} scale={0.048} />
        <group name="WGT-rig_foot_spin_ikL" position={[0.291, 0.08, 0.017]} scale={0.097} />
        <group name="WGT-rig_foot_heel_ikL" position={[0.275, 0.273, 0.008]} scale={0.097} />
        <group name="WGT-rig_foot_ikL003" position={[0.291, 0.08, 0.017]} rotation={[3.134, 0.194, 3.119]} scale={0.226} />
        <group name="WGT-rig_thigh_parentR" position={[-0.344, 0.638, -0.012]} rotation={[1.489, 0.191, -0.12]} scale={-0.047} />
        <group name="WGT-rig_thigh_fkR" position={[-0.344, 0.638, -0.012]} rotation={[1.489, 0.191, -0.12]} scale={-0.189} />
        <group name="WGT-rig_shin_fkR" position={[-0.308, 0.453, 0.003]} rotation={[1.541, 0.185, -0.13]} scale={-0.183} />
        <group name="WGT-rig_foot_fkR" position={[-0.275, 0.273, 0.008]} rotation={[1.526, -0.085, 1.08]} scale={-0.193} />
        <group name="WGT-rig_foot_fkR001" position={[-0.291, 0.08, 0.017]} rotation={[-0.02, 0.217, 3.076]} scale={-0.225} />
        <group name="WGT-rig_thigh_ikR" position={[-0.344, 0.638, -0.012]} rotation={[1.489, 0.191, -0.12]} scale={-0.189} />
        <group name="WGT-rig_thigh_ik_targetR" position={[-0.263, 0.482, 0.371]} rotation={[3.062, -0.123, -0.005]} scale={-0.047} />
        <group name="WGT-rig_foot_ikR" position={[-0.275, 0.273, 0.008]} rotation={[-Math.PI, 0, 0]} scale={-0.193} />
        <group name="WGT-rig_VIS_thigh_ik_poleR" position={[-0.308, 0.453, 0.003]} rotation={[-Math.PI / 2, 0, -0.32]} scale={-0.372} />
        <group name="WGT-rig_thigh_tweakR" position={[-0.344, 0.638, -0.012]} rotation={[1.489, 0.191, -0.12]} scale={-0.047} />
        <group name="WGT-rig_thigh_tweakR001" position={[-0.326, 0.546, -0.005]} rotation={[1.489, 0.191, -0.12]} scale={-0.047} />
        <group name="WGT-rig_shin_tweakR" position={[-0.308, 0.453, 0.003]} rotation={[1.541, 0.185, -0.13]} scale={-0.046} />
        <group name="WGT-rig_shin_tweakR001" position={[-0.291, 0.363, 0.005]} rotation={[1.541, 0.185, -0.13]} scale={-0.046} />
        <group name="WGT-rig_foot_tweakR" position={[-0.275, 0.273, 0.008]} rotation={[1.526, -0.085, 1.08]} scale={-0.048} />
        <group name="WGT-rig_foot_spin_ikR" position={[-0.291, 0.08, 0.017]} rotation={[-Math.PI, 0, 0]} scale={-0.097} />
        <group name="WGT-rig_foot_heel_ikR" position={[-0.275, 0.273, 0.008]} rotation={[-Math.PI, 0, 0]} scale={-0.097} />
        <group name="WGT-rig_foot_ikR001" position={[-0.291, 0.08, 0.017]} rotation={[-0.02, 0.217, 3.076]} scale={-0.225} />
        <group name="WGT-rig_root" scale={3.888} />
      </group>
    </group>
  )
}

useGLTF.preload('/mushroom.glb')
